version: '3.7'


services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8100
        volumes:
            - .:/code
        ports:
            - 8100:8100
        depends_on:
            - db
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data: